### PR TITLE
conditional DCGAN on MNIST

### PR DESCRIPTION
**Pull request by mohamad-hasan-sohan-ajini**
Hi

I add a conditional DCGAN example. The images generated by G is placed at the end of notebook. The images have higher quality than that of CNTK example.
The example also is similar to (this CNTK tutorial)[https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206B_DCGAN.ipynb]. Except that conditional GAN have an extra conditional input, dictate the G what to generate.
Please inform me if there are inconsistencies whit your repo.

regards
Ajini

### CODE REVIEW

**Comment by astorfi** [comment]
@hajix Thank you for your pull request. I will investigate it and get back to you.

**Review by astorfi — CHANGES_REQUESTED** [review]
Would you please create more descriptions and comments for your functions?
Please follow the rules of commenting and function description as provided in [this link](https://github.com/astorfi/speechpy/blob/master/speechpy/processing.py).

**Comment by mohamad-hasan-sohan-ajini** [comment]
some docstrings added to function definitions.
Please check it out.

**Comment by astorfi** [comment]
@hajix Thanks for the docstring and modifications.

**Review by astorfi — APPROVED** [review]

**Review by astorfi — CHANGES_REQUESTED** [review]
I think the following part of the code may cause issues since the visualize function is called more than one:

    if os.path.isdir(p):
        shutil.rmtree(p)
    os.mkdir(p)

A suggestion is that you create the folder at the beginning of the code and once. I am still reviewing it though. 

Besides, currently, I am getting the error "No such file or directory". Possibly it is due to having '/' in the path. Please refer to [this link](https://stackoverflow.com/questions/27832648/no-such-file-or-directory-from-os-mkdir) for more information.

**Comment by mohamad-hasan-sohan-ajini** [comment]
There must be a directory called `samples` beside code, to avoid error. After some epochs, samples generated by G will be saved in a directory with relevant name (epoch00099 for example) in `samples`. The snippet you mentioned is to create sub directories in `samples`. Unfortunately git does not support empty folder so it does not uploaded by pushing changes. I'll add a newline to create `samples`directory at the beginning to solve the issue.

Please tell me if there is a better way.

**Comment by astorfi** [comment]
@hajix Thanks for your attention. Yes, you are absolutely correct about empty folders issue. Your solution is good for creating it at the beginning of the code. Please update your pull request with your suggested changes.

**Review by astorfi — APPROVED** [review]

**Comment by astorfi** [comment]
@hajix Thanks for your changes ... I am testing the code now and will get back you very soon.
In the meantime please do some cleaning up in your code (ex: cleaning commented codes and useless comments) and add some explanations for the code in its above part (with some referred links) ... Thanks for your consideration.

**Comment by mohamad-hasan-sohan-ajini** [comment]
what do you think about progress print functions? You used `C.logging.ProgressPrinter` in your examples but I think they make notebook ugly and long with no good reason. Instead I use `C.logging.TensorBoardProgressWriter` which is cleaner in my sight by it need the user know about tensorboard. Is it better to uncomment them or remove them?
```
#D_progress_printer.update_with_trainer(D_trainer)
#D_progress_printer.epoch_summary()
```

**Comment by astorfi** [comment]
@hajix You are absolutely correct about the benefits of ``C.logging.TensorBoardProgressWriter``. However, I did not use it since it requires a knowledge about Tensorboard as you mentioned and I have not prepared any tutorial about the Tensorboard yet. So let's make it more simple now and stick to simple ``C.logging.ProgressPrinter``.

**Comment by astorfi** [comment]
@hajix If you think you want to make any changes I will wait unless I would be happy to merge it. Later I may want to do some minor changes myself. Moreover, Please add the documentation at the beginning of the code.

**Comment by astorfi** [comment]
@hajix Thanks ... I would be happy to merge it!

**Comment by mohamad-hasan-sohan-ajini** [comment]
I think this pull request takes too long, although now I'm more familiar with repo structure. Thanks for your patience and guidance. @astorfi

**Comment by astorfi** [comment]
@hajix My pleasure!

**Pull request merged**
